inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'test/encoding_test/*.rb'
    - 'devel/levitate.rb'
    - 'devel/levitate_config.rb'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6

# Make BeginEndAlignment behavior match EndAlignment
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

# Be lenient with line length
Layout/LineLength:
  Max: 92

# Don't force lonely closing parentheses
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Force consistent spacing independent of block contents
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Tests use blocks that define constants
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'

# Needed for `unfixable` in tests
Lint/SuppressedException:
  Exclude:
    - 'test/**/*'

# LiveAST sometimes needs to rescue all exceptions
Lint/RescueException:
  Enabled: false

# Allow test classes to have any length
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# Allow use of eval in tests (that is sort of the point!)
Security/Eval:
  Exclude:
    - 'test/**/*'

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Allow multi-line blocks of all sorts
Style/BlockDelimiters:
  Enabled: false

# Allow def A.foo in tests
Style/ClassMethods:
  Exclude:
    - 'test/**/*'

# Stack trace is less important in tests
# TODO: Look into details later
Style/EvalWithLocation:
  Exclude:
    - 'test/**/*'

# Stop this cop from complaining about us-ascii encoding
Style/Encoding:
  Exclude:
    - 'lib/live_ast/reader.rb'

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Allow both lambda syntaxes in tests
Style/Lambda:
  Exclude:
    - 'test/**/*'

# This test requires its constant to be mutable
Style/MutableConstant:
  Exclude:
    - 'test/full/replace_eval_test.rb'

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Use {} for %-literals, and revert to previous RuboCop default for %w
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%w': ()

# Allow Proc.new in tests
Style/Proc:
  Exclude:
    - 'test/**/*'

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Allow multiple expressions per line
Style/Semicolon:
  AllowAsExpressionSeparator: true

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets
